// Generated by https://quicktype.io

export interface NaverNewsDataObject {
    data: NewsData;
    status: number;
    statusText: string;
    headers: { [key: string]: string };
    config: Config;
    request: Request;
}

export interface Config {
    transitional: Transitional;
    transformRequest: null[];
    transformResponse: null[];
    timeout: number;
    xsrfCookieName: string;
    xsrfHeaderName: string;
    maxContentLength: number;
    maxBodyLength: number;
    headers: Headers;
    params: Params;
    method: string;
    url: string;
}

export interface Headers {
    Accept: string;
    "X-Naver-Client-Id": string;
    "X-Naver-Client-Secret": string;
}

export interface Params {
    display: number;
    query: string;
}

export interface Transitional {
    silentJSONParsing: boolean;
    forcedJSONParsing: boolean;
    clarifyTimeoutError: boolean;
}

export interface NewsData {
    lastBuildDate: string;
    total: number;
    start: number;
    display: number;
    items: ArticleData[];
}

export interface ArticleData {
    title: string;
    originallink: string;
    link: string;
    description: string;
    pubDate: string;
}

export interface Request { }
